name: Build Docker Container

on:
  push:
    branches:
      - main
      - master 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: "{{defaultContext}}:02_CODE/docker_apptainer_hpc"
            file: Dockerfile.ubuntu24.04.ifort
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/hfe_development_ifort:latest
            build-args: |
                GITHUB_USERNAME=${{ secrets.USERNAME_ADMIN }}
                GITHUB_TOKEN=${{ secrets.TOKEN_ADMIN }}
                USER_UID=1000
                USER_GID=1000
