name: docs_pages_workflow

# Execute this workflow automatically when we push to master
on:
  push:
    branches: [ master ]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y git rsync python3-sphinx python3-sphinx-rtd-theme

    - name: Execute script to build our documentation and update pages
      run: bash 02_CODE/src/docs/buildDocs.sh